apiVersion: kustomize.config.k8s.io/v1beta1
namespace: monitoring

resources:
  - cluster-role.yml
  - config-map.yml
  - daemonset.yml
  - deployment.yml
  - ingress.yml
  - pvc.yml
  - service-account.yml
  - service.yml
