apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cnpg-freshrss-user-secret
  namespace: database
spec:
  secretTemplates:
    - name: cnpg-freshrss-user
      stringData:
        password: ENC[AES256_GCM,data:rUqzBgT2/GJ64vG+KVqRWw==,iv:m8viCLh974Lpw6CZjK7U7H6yN0YRwV0vxmmw1sphia4=,tag:9nwe0WZFfUhvNPrPpXYU7Q==,type:str]
        username: ENC[AES256_GCM,data:ESF1La42SUw=,iv:wE4u+bFOIovHowgB90ISAtKD9/r1ek762K7RwUITw9E=,tag:c6usHS6L9sLUC6Yf3v9zWA==,type:str]
sops:
  age:
    - recipient: age1cnhy4vhemg9lat9ja5v4e7h7qan5r2rwdkl6qgwjxmhhrusqr36q4er848
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNFYvWElZQm1wN0ZsR2s5
        bUhWVlVLbE9hM3BsQkRqOVVkdWRRdlAwR1hnCkl3VmxHZWNndlVOZ25TUTJzYVpi
        dWFFbC95VjlUalFMTTh1ekpYRVBzbXMKLS0tIGhSdXBRRk5BQ0JTZkdWZ0VXbGxI
        VHFOWHA0elVkc1hFcUVCd3FHaWh4TTAKtPGZmMkz15V+Ya32WuyeDdUv+xqCZD4Y
        pZ7NIbaljaL0efHQdoM2KfUWYcoaYgr/Rhzyaz3GeDwd/5TyhuPq3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T14:20:00Z"
  mac: ENC[AES256_GCM,data:ee9g0BJivMd66qDzXoeE3z0qCs+dJ/jdeT2cxcsRnfkwSG5jW7FmsuVXlgpltgK1Iz6fGxXeKNC1y1JZo7/IGqIhFUkqt5NG6yK1CLRtbr4PC/O0Hz++b/Db6nWsLhIG/sKhI8UruMlSKgNvNt1uSuPNpEyVeGq7MO75W3r9bbA=,iv:8I8bhJ2XUm8rk31UWQtlnqqm20cExAE/2M8jUf+34aA=,tag:veNEs2eSFuXmctPT79d5mg==,type:str]
  encrypted_regex: ^(secret|id|token|data|stringData)$
  version: 3.11.0
