cluster:
  instances: 1
  storage:
    size: 10Gi
    storageClass: "local-path"
  monitoring:
    enabled: true
    podMonitor:
      enabled: true
    prometheusRule:
      enabled: true
  roles:
    - name: atuin
      ensure: present
      comment: atuin
      login: true
      superuser: true
      passwordSecret:
        name: cnpg-atuin-user

    - name: wallabag
      ensure: present
      comment: wallabag
      login: true
      superuser: true
      passwordSecret:
        name: cnpg-wallabag-user

    - name: seaweedfs
      ensure: present
      comment: seaweedfs
      login: true
      superuser: true
      passwordSecret:
        name: cnpg-seaweedfs-user

    - name: freshrss
      ensure: present
      comment: freshrss
      login: true
      superuser: true
      passwordSecret:
        name: cnpg-freshrss-user
backups:
  enabled: true
  retentionPolicy: "15d"
  destinationPath: "s3://maskudo-homelab-backups/cnpg/"
  s3:
    region: "ap-south-1"
  secret:
    create: false
    name: "s3-backup-credentials"
  wal:
    compression: gzip
