cluster:
  instances: 1
  storage:
    size: 10Gi
    storageClass: "local-path"
  monitoring:
    enabled: true
    podMonitor:
      enabled: false
    prometheusRule:
      enabled: false
  roles:
    - name: atuin
      ensure: present
      comment: atuin
      login: true
      superuser: true
      passwordSecret:
        name: cnpg-atuin-user

    - name: wallabag
      ensure: present
      comment: wallabag
      login: true
      superuser: true
      passwordSecret:
        name: cnpg-wallabag-user

    - name: seaweedfs
      ensure: present
      comment: seaweedfs
      login: true
      superuser: true
      passwordSecret:
        name: cnpg-seaweedfs-user
