apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: sops-secret
  namespace: database
spec:
  secretTemplates:
    - name: s3-backup-credentials
      stringData:
        ACCESS_KEY_ID: ENC[AES256_GCM,data:YTxmCGdx9sfShoEby1yDBD0nP6g=,iv:sVi3ky/vyYVRY2SnHzPECYLKzxf4r4AvtgugOu07994=,tag:N4zhJC0M57Cloq3C16pZgA==,type:str]
        ACCESS_SECRET_KEY: ENC[AES256_GCM,data:xpaiXRZO7zxHfLn4Y3mtMp7IIBKVjGjbRSfUtkVGqQAGeb5mEMlHqg==,iv:YZxbAqYzIOYP3ilrevcLUC48C8TgHCDblZnqCq3zrfE=,tag:qzX5tVFBndwosEOy8RdNTw==,type:str]
        AWS_REGION: ENC[AES256_GCM,data:fLbHidNfxQJLjA==,iv:g9jpAkGh3hYZeZQssOT3WI0VJhEjcSH45ZRz5t1sXlE=,tag:FTSrVe72G6CyaspQypdXAw==,type:str]
sops:
  age:
    - recipient: age1cnhy4vhemg9lat9ja5v4e7h7qan5r2rwdkl6qgwjxmhhrusqr36q4er848
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RWhnTExHVzRSaU9CSmJ4
        cllTbEJ6azhLRjRYNE5VRTFueVBHeHltSW53CkE5MHFoekxPZkJrK0Nnc3A5aHNy
        cnBYaXpReEI4RXBZRy9hUjVZRldUV2cKLS0tIGIrblM3MTFibUsyeTFJRm9LL2tB
        ZFRZSHh6bWFlTkNDdUF2SFMxejZLZ1UKfEueMauDw3qg+cW5Ck8oZvUCl8xFrydU
        Pi65QBR8Q2dLYjr/439GZqUxtzQu3UqrPmmS6sHZi/wCbldJy2HItg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:19:04Z"
  mac: ENC[AES256_GCM,data:Zn2t2V+osyDiVzBQUspqoAWqp9a4s3gQCeTJzVUytq4LUGYKR6e4YQLSDeSXErDhDilH/+/lDRJQhppMDK4iBZObktz601rLZYypnAD176/TcykKJ7Jw6Vl6sGwdhQbdgSwXY+qTS2Z7MNgZk2Nix2foR/10dK93nj9+k/Ml7M0=,iv:DBRyr06d0cTcAKK9Oq+CDS/HsguO8nZSJgOvyNkQXG0=,tag:OTOcpWNV6oOpzZAJSSMPlA==,type:str]
  encrypted_regex: ^(secret|id|token|data|stringData)$
  version: 3.11.0
