apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  tls:
    - hosts:
        - music.manujkarki.com.np
      secretName: apps-certificate-secret
  rules:
    - host: music.manujkarki.com.np
      http:
        paths:
          - backend:
              service:
                name: navidrome
                port:
                  number: 4533
            path: /
            pathType: Prefix
