apiVersion: v1
kind: Service
metadata:
  labels:
    app: navidrome
  name: navidrome
  namespace: apps
spec:
  ports:
    - name: navidrome
      port: 4533
      protocol: TCP
      targetPort: 4533
  selector:
    app: navidrome
  type: ClusterIP
