apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: wallabag-secrets
spec:
  secretTemplates:
    - name: wallabag-secrets
      stringData:
        SYMFONY__ENV__DATABASE_DRIVER: ENC[AES256_GCM,data:2w6cZEgQ90AB,iv:UqXXg7kg2w/zvzuw1+gtX2EC7Xr58f9tBzWaYZ23xv4=,tag:d4W+mzA+X8RxcuKcXckL/Q==,type:str]
        SYMFONY__ENV__DATABASE_HOST: ENC[AES256_GCM,data:Jnvh6abswEMjXGF5+yjLbDgHF66Dwtd+,iv:TpDpZ5b92klizo6fucqQO3cvrmL3vuufOMZH1nQWMSo=,tag:K/PfxoZkRakXykcv27UCoQ==,type:str]
        SYMFONY__ENV__DATABASE_PORT: ENC[AES256_GCM,data:ta4pQg==,iv:0gON16vWyVwKCmKm7PBQ22g4tjtd9SDf1b8nXIfcPRQ=,tag:9aLGBT1Xgdlz/S7spCgRWg==,type:str]
        SYMFONY__ENV__DATABASE_NAME: ENC[AES256_GCM,data:tXMMz6PizxY=,iv:6TtaOLDmLg8REuFraiL3w2RL9NHKV2JjNtihXGqVsfw=,tag:GWMHwvOXOXKz8Olx26f3sQ==,type:str]
        SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:wPaaiB8Pp40=,iv:nedfRISoqrmDFP9tC3X+UZ9mfNjDSPidu+jidq2DOFk=,tag:IP+7xaHBcqNBcsK9tO7Erw==,type:str]
        SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:Y4qJlv/B0OcTRHe2,iv:4Lk5tHamw5s3G0CvM4mCqMb7hVWp3JnwOB8a2jsQu98=,tag:M9HhCXyTZvqMlhJ/akg90w==,type:str]
        SYMFONY__ENV__DOMAIN_NAME: ENC[AES256_GCM,data:Xa5S6+za0em9B7ZfJsHIj2vHBjZAiwqLAvLajLv6qXsLMw==,iv:nL2OVXDyT2hzqFwwKpHGGgzryw/Q2c+QVaMWKy0C1/M=,tag:Q3QhfkH02y1xZ2gEOo14hA==,type:str]
        SYMFONY__ENV__SECRET: ENC[AES256_GCM,data:4YBrsEo5bQKW+tVgtNMwWdIzreg5R1OeAkmCrwv65/b9aYogf+eTnwKaDExOBUZp66eOow==,iv:0wUTrosY3So/+1pX/2TZrlVLT2MX+EphGDtBrDXxXgc=,tag:LQlNoUhaxeVqEHBxqm7YYg==,type:str]
        SYMFONY__ENV__FOSUSER_REGISTRATION: ENC[AES256_GCM,data:Lv5ggg==,iv:nIGrt0G0mVirFf9WFrKfVoZlMWbKkFiUVjjP9l+t/LM=,tag:KW8kf0EQKMPqVBcDL19wZA==,type:str]
        SYMFONY__ENV__FOSUSER_CONFIRMATION: ENC[AES256_GCM,data:m0TYwZ8=,iv:B9iN3zNTyw38hjUzziEZk3dCKSaHCF8dI/wVwAkMPg4=,tag:YzDZLIzFC7MwEzhDELQRGQ==,type:str]
sops:
  age:
    - recipient: age1cnhy4vhemg9lat9ja5v4e7h7qan5r2rwdkl6qgwjxmhhrusqr36q4er848
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaUJZdzdjN2t0em1MTUNJ
        Vk1qczEwZk1KT3FRU3dvZnlEZzdtTnB4MWtZCndmSHBib1JMYUFPR00waW9ZRDNO
        YlZFeENKTnJqOUJESElTYUxGcUF3TmMKLS0tIDc3ZWJEd1d6N29DVWdTUDBZZ2lq
        WGlPVDFYcHdTdm9IdERiQVBXSEhuVzQKrNVN+enODON5KIfxt0riyi7MUJezv9RG
        HfhVQ70QTzUFhrtXFkSXr7nORFLL2S0bEX0VYtySdzo7GnIpfQgO9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T14:20:37Z"
  mac: ENC[AES256_GCM,data:LmmSFx1egN9MnmOaV0MUfEErOfY1ZkS0Cu7U+/NVDdLxObicDpCiIUswv4h4wrj2Y4B6yjwSuozAy5B4rXgWQzY/6Qu6ybBOYyaoS5RMEwUbjGZQbkDvq09dc6EizW617VSgYamEExKWO38Fl905ljhw5g5z88GzsAQX4601KEQ=,iv:E+/XxgtKOtZwmrWayREz7eN2Pc+Qttp9IEjRbHP6pBU=,tag:RoXEHpPIO9FfocT8egG8Qg==,type:str]
  encrypted_regex: ^(secret|id|token|data|stringData)$
  version: 3.11.0
