apiVersion: v1
kind: Service
metadata:
  labels:
    app: wallabag
  name: wallabag
spec:
  ports:
    - name: wallabag
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wallabag
  type: NodePort