apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cnpg-atuin-user-secret
  namespace: database
spec:
  secretTemplates:
    - name: cnpg-atuin-user
      stringData:
        password: ENC[AES256_GCM,data:k8+qs2OCVssq,iv:w9WymHS6p1i+E7SHb13AgHTZNATnLC3zBozlGPrne/w=,tag:psT4Slx2hhyi307hwKLxNg==,type:str]
        username: ENC[AES256_GCM,data:S9cGpqQ=,iv:R73ezRrua5o36YnMzdydsni0Hk1G7fdV2H7Orjhs2pw=,tag:6TtLBjXrGvSUzgMiYamr0A==,type:str]
sops:
  age:
    - recipient: age1cnhy4vhemg9lat9ja5v4e7h7qan5r2rwdkl6qgwjxmhhrusqr36q4er848
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bUR1MGJqNExkNUg5dUlI
        d3Y3MnZGM0NBcEJ1UXFjWUFjUzlrdjRQMTFFCmVYOFozNW9MbXVGdWJLRWRYZ1JX
        QmdGdWFWK2E4QXprM1JBZDJDaDB0SncKLS0tIDhWTzBQQlU5NTBOSHJIeDhUckJn
        N0RxTXhLdUsyM3dZSWpteDhNQ2NNWmMKTcqLccxx3XM0lhGJp4iRkaE+gGc13E8C
        75lnIzcy/F7kTCCF/zxO1AFaRe5fk6k2VAnvXok6zDez9gfNxC8nDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T17:53:22Z"
  mac: ENC[AES256_GCM,data:YwMp6tGQA1+2+u97zooi2XN2C0hjOFO0HA5C3Xgv+XDyhnzuPUeLVumm6DzhpDOVVAbNI/M7nDErwLrfRJENgEhVK6hgVXdmEwk+XpujBW/XnstNXsZiubJevLZmsO72iUVmBrn34D0X90fzX4UvwFDx0i85lzOgJMdxlf8oKvA=,iv:fdTs39jzoS5c8VXgRmnJTXjqkVtcUR20dbuauh5Zzsc=,tag:tJfRrIpmWFGKKXI/ReFl1A==,type:str]
  encrypted_regex: ^(secret|id|token|data|stringData)$
  version: 3.11.0
