apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atuin
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  tls:
    - hosts:
        - atuin.manujkarki.com.np
      secretName: apps-certificate-secret
  rules:
    - host: atuin.manujkarki.com.np
      http:
        paths:
          - backend:
              service:
                name: atuin
                port:
                  number: 8888
            path: /
            pathType: Prefix
