apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: atuin-secrets
spec:
  secretTemplates:
    - name: atuin-secrets
      stringData:
        ATUIN_DB_USERNAME: ENC[AES256_GCM,data:pQxovCs=,iv:GtNJGb08StMmGdsu4cnqha9QS01jvbRoGials61fWH8=,tag:2c5yR1LKFa3ihZoaJlIuSw==,type:str]
        ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:3aHfVfzAakG3,iv:2vlTh9xCBIusKn4jiCCZAxUHT56EMKRbFqZXViEjp3w=,tag:kauQtsjoXmvt9/RQSx3CDw==,type:str]
        ATUIN_DB_HOST: ENC[AES256_GCM,data:HI+M9A1APrpkrEutGUWzkT6liySjYg70,iv:DJAtoLScUn9utVBsPgTHFMlvQhl71hdx5pXWnHI8UTE=,tag:hRNSZeYDlPt0dKONfscMog==,type:str]
        ATUIN_DB_PORT: ENC[AES256_GCM,data:JiL0+Q==,iv:JrJ9RSRA3hqlz8GjrG5PL6McGzjaQMaAXuNkqb1Nwt0=,tag:nfLBY9gbUO4PbTxkT4Cz6Q==,type:str]
        ATUIN_DB_NAME: ENC[AES256_GCM,data:yDSQAi4=,iv:UH5x896v6TfpCPpn0/6ru15d+rLb+RNP1sV6iDCgq0M=,tag:lTUAwOWVS+X1pudFDBjZdw==,type:str]
        ATUIN_DB_URI: ENC[AES256_GCM,data:o7AztuZ8QThLpt+RRcMj1cBa6py9289SGoGm0CABfunn+dx5VQpB/JYJXD1GiXOqwbg7evKcPVA2sQxzhWG+8w==,iv:kIafUiOcJ1+Wfwr0Cn4ptiQeUbKzuKJyNxnIliVbs90=,tag:LWA+gxKvUkPur/LLABwdmg==,type:str]
sops:
  age:
    - recipient: age1cnhy4vhemg9lat9ja5v4e7h7qan5r2rwdkl6qgwjxmhhrusqr36q4er848
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb2MzWUUvNERnWUp4azdS
        SFlKMjlQRlB3NlpQMXkweFJ2emRWQ0laNVYwCmR0QXRZS0I1QmYyRGdoYTY5MUtV
        YXljYWRiQnI2czMyUFU2UHU5RDVLV2sKLS0tIGpydEUvVjZqYVNaRFJhZjhZR25n
        eFl4R0NwcllteXZwL2NiZkd0WEZhb3cK0jR8fT+UrHvgwRvKmPUnmuWOOphKRXZT
        kg3mxgo1+7lHVWuJGrPItzNqzWn5sK+Vp6YQ19E0uXxV8GeWDDBlCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T18:43:09Z"
  mac: ENC[AES256_GCM,data:qWhtMXaAuYk6DaTYfdIXuNzWj2uHF/kXpopYhn172XdPxU6WhXijMnp5yhY1+L4vdxFy2lR8jNxyblyrEqxW+TBOpY2buM/3r8/ywrzRJ2NnTMVSKmh60PfsIEjTxl4zwLg9SNNBBRuB2LVfOfRElxRgJtHAzTGuLq9AiP2fchY=,iv:/fsR1Z6Vo3sIJpW0ZBO17jwV0LD+r8blXCNzSBDNvd4=,tag:YBMndUGHV7ckllmv6uXAfA==,type:str]
  encrypted_regex: ^(secret|id|token|data|stringData)$
  version: 3.11.0
