apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-certificate-secret
  namespace: longhorn-system
spec:
  secretName: longhorn-certificate-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.manujkarki.com.np
