apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-certificate-secret
spec:
  secretName: apps-certificate-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.manujkarki.com.np"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "apps,cert-manager,kube-system,longhorn-system,monitoring,traefik,default,argocd" # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "apps,cert-manager,kube-system,longhorn-system,monitoring,traefik,default,argocd" # Control auto-reflection namespaces
