repositories:
  - name: kube-prometheus-stack
    url: https://prometheus-community.github.io/helm-charts
---
releases:
  - name: kube-prometheus-stack
    namespace: apps
    chart: kube-prometheus-stack/kube-prometheus-stack
    version: 81.5.0
    values:
      - ./values.yml
