kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-data
spec:
  storageClassName: nfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-redis
spec:
  storageClassName: nfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-postgres
spec:
  storageClassName: nfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
