apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cnpg-seaweedfs-user-secret
  namespace: database
spec:
  secretTemplates:
    - name: cnpg-seaweedfs-user
      stringData:
        password: ENC[AES256_GCM,data:898Y0PL9BGy1tPddwg==,iv:L3AiIyp49fvmlVqYxi6CK+tNjIwP3N+269J+FUvJnjs=,tag:bwMCbDNt1r/LVUQ6oxZOZw==,type:str]
        username: ENC[AES256_GCM,data:QhWEqs2c3zv5,iv:SL4a6iN+3zAh74PUl3Z1a3238QefFSILN9ARXCYYIt4=,tag:GwyQlivAjJ6E4bgQ4UYoFg==,type:str]
sops:
  age:
    - recipient: age1cnhy4vhemg9lat9ja5v4e7h7qan5r2rwdkl6qgwjxmhhrusqr36q4er848
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOUt0V3JyMGJyZE95TUls
        MVp0SW12RmlhQWxPcGkxcWwwVUd3NTlQMjBRCkhyUTh3b3kzNXJIdmd2S09hZ1dN
        d1hHMnJzQ3dBWWxBemxONk4xRW9IV3cKLS0tIGRkN1pYbmQ3dGxYa2VINHpnb1Ay
        M1pTK3FzYTZXT002bTdjYy9PcG4vWEUKA2BqISGAENa/QreTwoaMp9frIvOBmJQK
        LtYkAwa7OV96RN6haRQlQaZaDaqnfXGvU/8Ctf081nPK1lv1WtlyaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T15:15:55Z"
  mac: ENC[AES256_GCM,data:ixgcaz1V/3RXB7je9Pi59Qay7rN+ywtLSaOM/6hthQVpqYh4Zhk3vyc/rHyVRN1oev82YfkagmV2SU0l7EfyCczMzGeLkevDaRTIE9dbwIdZ9Q0xItvREFV4X6X2ABfja2DoojHG9LNRKp7QFplPPxsKv5ioCUvpgOPdgrIzQ/U=,iv:koTQzJKMPzHZklA9CYduVTuKd49FRGwPyVnhLlx7m7g=,tag:APXQNuw8nvK5NLQGTogu8A==,type:str]
  encrypted_regex: ^(secret|id|token|data|stringData)$
  version: 3.11.0
