apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: seaweedfs-secrets
  namespace: apps
spec:
  secretTemplates:
    - name: seaweedfs-secrets
      stringData:
        POSTGRES_HOST: ENC[AES256_GCM,data:GI7EURCiQjiPK7gBBDDwcbGgpIJBRGDB,iv:UsfqmuLJ2Lt0g+QUm6GvgGCTxkQAsX/+mTi6Adjwd7A=,tag:601wUap1mfOA2nNFIWX7ng==,type:str]
        POSTGRES_PORT: ENC[AES256_GCM,data:2DlF5Q==,iv:tWGmdDl2yExJu3AldmKEBKYcJTZ/vYF85s49HVYHAAM=,tag:E66lb7sPkMn9n90Huq8LMw==,type:str]
        POSTGRES_DB: ENC[AES256_GCM,data:ik8y2Ph16bF9,iv:8jKQh3FJO7HDq3JCtisW8Gwbj04X7jHvwzTJaCXCzrE=,tag:VMoVuMtWqvJQGJXK4Tq4iQ==,type:str]
        POSTGRES_USER: ENC[AES256_GCM,data:EGTywGWhyu2j,iv:WZV26rRa0L06Igl9KqN9zEiZZyuS5W2QFeorwwd4l0U=,tag:BF7DS/31GMQwtq3dAq2l/g==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:Aza0AzJTHCPXzV1irA==,iv:DuiV5ieikDSd2gU2UaGB6uRgJgb8PkbFj0d0VIs0ytQ=,tag:1jQNez6QuPl7O08wqnyaug==,type:str]
sops:
  age:
    - recipient: age1cnhy4vhemg9lat9ja5v4e7h7qan5r2rwdkl6qgwjxmhhrusqr36q4er848
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMC9JSGdKQmplangrVUp0
        cWNBa3JsdHg5UUhnVmlBZjZpOW5teVA4cldRClU5WFZuc0o5bWVnSkM1Vnl6WExY
        N1pBcGhyQmhMQkFCQ2E3dWJjVFhkMUUKLS0tIGdhYmNrY0tCL0tza2VGeWtUUlRX
        NjZ0TnlhVkhQVjFuZ3Fvb204eU41eXMKfFDPQE9+CESgqCxRWDGb4gUOC7HIcji5
        Lj3PWOM+cwfw/soh7ikUWEcLhASlRILECTJfDKjYnmo0S1CCHkVtzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T15:12:40Z"
  mac: ENC[AES256_GCM,data:T6daTz9IvkoP+0pXg4GZVAkPp9Mwnuga1+gqVtXw84+hobaFgo69qkmPciF+D0Q/1pASZAadVfSkUzLNUnYC3PhBrC0qY4OY9wFVNh6LUrZ4teGM1I84R575EdhEZ082gDytKkaEz7n1fx1kn0QluOIbL0PcG3wwx4TAqAuoTOA=,iv:7j0gVgDJTNr54MWcFKBr0oBVZCJhuOhczNjUqLbOIuc=,tag:H0FrlUsJakegMbDw/hLbcw==,type:str]
  encrypted_regex: ^(secret|id|token|data|stringData)$
  version: 3.11.0
