apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: seaweedfs-web-user-secrets
  namespace: apps
spec:
  secretTemplates:
    - name: seaweedfs-web-user-secrets
      stringData:
        adminUser: ENC[AES256_GCM,data:ILYYlT8=,iv:HFdmfJkCwQLQhfcFCFk2wBjB4l+u8EVhWJ/nube0MrE=,tag:7RXtHs/cgK9umptDzJsELQ==,type:str]
        adminPassword: ENC[AES256_GCM,data:7zC1wVJEzmsLuqmQzQ==,iv:VGFZvt6jv8CvOicDjyL76VhtuUpsMyxtFOdAWDuCIfs=,tag:2XVTMzLWQ1x/z6FMCeUCqA==,type:str]
sops:
  age:
    - recipient: age1cnhy4vhemg9lat9ja5v4e7h7qan5r2rwdkl6qgwjxmhhrusqr36q4er848
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQU1hbHFLVTd1YnZqRUkr
        dGIzTXAxeS9EbTA2NzVreTgyUHRJdHY3U25BCjJzK3djbGE4QS9LVkQ5bGhsYUg4
        YVBtVUl3amI0RW5mQWNQalhMeXdPWFEKLS0tIEQwMkNySW9uSWwyK0hpRjVRM3NQ
        czNuUkkzZ09FcnFVNzV3TUFKTVA4VjAKxyDCvMQ+Ip6RqnGbPM85jIIaLgwF0hCR
        fZgbNSPxj9nM1wwSy5eL/+h8pZCS50pcZdTe8M97S0CuQtQuuInEsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T15:52:17Z"
  mac: ENC[AES256_GCM,data:hTtidccFv/GNDoOSWagREvE+hqSu83pzjpgqlpBuaIWCw+ItwJQ1lpWxUAJdI0OaZPpXi2OyPe/XN0Zbq6os7QRizZAY5/T2O6JYRUMjuxnH9AGiOE69b7/NIPL9z+k1YpGyLouYVitNt9cSXE8ziJHrn1TE42HhNu40w47RzV8=,iv:0cyGWHinEjQ96aCB/iT+s/2kRTP4mNJCp3IEvsbSSSk=,tag:JwqvLiUs4SxunCVgsMYCtQ==,type:str]
  encrypted_regex: ^(secret|id|token|data|stringData)$
  version: 3.11.0
