---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.1.78:
    agent:
      hosts:
        192.168.1.79:
        192.168.1.80:

  vars:
    ansible_user: ubuntu
    ansible_port: 22
    k3s_version: v1.31.12+k3s1
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

    # Disable Traefik
    server_config_yaml: |
      write-kubeconfig-mode: "0644"
      disable:
        - traefik
