apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/maskudo/homelab"
      targetRevision: main
      ref: src
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      chart: csi-driver-nfs
      targetRevision: 4.12.0
      helm:
        valueFiles:
          - $src/k8s/csi-driver-nfs/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
