apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/maskudo/homelab"
      targetRevision: main
      path: k8s/freshrss
    - repoURL: "https://github.com/maskudo/homelab"
      targetRevision: main
      ref: src
    - repoURL: https://charts.christianhuth.de
      chart: "freshrss"
      targetRevision: 2.5.2
      helm:
        valueFiles:
          - $src/k8s/freshrss/values.yml
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
