apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://isindir.github.io/sops-secrets-operator
      chart: sops-secrets-operator
      targetRevision: "0.17.2"
      helm:
        values: |
          secretsAsFiles:
            - mountPath: /etc/sops-age-key-file
              name: sops-age-key-file
              secretName: sops-age-key-file
          extraEnv:
            - name: SOPS_AGE_KEY_FILE
              value: /etc/sops-age-key-file/key
  destination:
    server: https://kubernetes.default.svc
    namespace: sops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
