kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-config
  namespace: apps
spec:
  storageClassName: nfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-metadata
  namespace: apps
spec:
  storageClassName: nfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-podcasts
  namespace: apps
spec:
  storageClassName: nfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-audiobooks
  namespace: apps
spec:
  storageClassName: nfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
