apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cnpg-wallabag-user-secret
  namespace: database
spec:
  secretTemplates:
    - name: cnpg-wallabag-user
      stringData:
        password: ENC[AES256_GCM,data:SlHVARir/Ex3AxTY,iv:KFddNAYYD3VYW/KoHbcI4wgr3pk/SYYiXyLyVE/TchY=,tag:wRHFOF5Qi70eTqFMt1vqmg==,type:str]
        username: ENC[AES256_GCM,data:XyYPEZZbYwA=,iv:cqM+n9seOnOZMcnZK+7KIdGTDeXc+Xz1y9gRfOAig/k=,tag:JTQu/wuwqXUyc6crAKzv1Q==,type:str]
sops:
  age:
    - recipient: age1cnhy4vhemg9lat9ja5v4e7h7qan5r2rwdkl6qgwjxmhhrusqr36q4er848
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYjRjTS9RVExScFBtTVNu
        eU01TnhhL0gxYy9vWE1YN3dYMmJvKzBkRlI0CmYvdlY1YVJOR3pVaForOFBOekVi
        aVExcW54ZTFtNldHSStpUk50d2ZJQkkKLS0tIGZ5VUwvN0Q1U2UrWEtIZm9rNmhJ
        ZlRoVENocGk3TWFBM2Z3RDVSUlNnL1EKPTHyNZ0LVMYwYFR8dQtq8yMNThq27p5W
        BvkRqdf6sja8m8/Y4XWH70mqJlBZryla1Fj+yrJMXnhozGBAi7rByw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T13:01:24Z"
  mac: ENC[AES256_GCM,data:3uZnOxkhsYqO7iD+4DMNl6oHtefShiwrlQotLYCl6Kfe5nWjTaWjyJVp4H+WDUGRaqgbLPYvuNbMX3mie18NxsTFO7JplCemgqnxcTCZudt3XJrOCJFYPnXnVi3Uv4UNOesrhwjXQXPdGSkuKah/yXuInGSd1PROHRzNa0+X4u4=,iv:e/UgUIYaVSYjtgmERIAjrZF59BQD1wlVIiHRk+3ElJk=,tag:c9EsYyhzBFdquBmNxsHLmw==,type:str]
  encrypted_regex: ^(secret|id|token|data|stringData)$
  version: 3.11.0
